name = "p5js_gleam"
version = "2.1.2"
target = "javascript"

description = "A simple game library providing p5.js bindings for Gleam in a functional style to make basic games and animations. Heavily inspired by the Racket library 2htdp/universe"
licences = ["MIT"]
repository = { type = "github", user = "Acepie", repo = "p5js_gleam" }
links = [{ title = "P5.js", href = "https://p5js.org/" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
